package ua.tqs.hw1.webapp;// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.assertj.core.api.Assertions.assertThat;
@ExtendWith(SeleniumJupiter.class)
public class AirQualityNowTest {
  @Test
  public void airQualityNow(FirefoxDriver driver) throws InterruptedException {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1536, 877));
    driver.findElement(By.id("location-input")).click();
    driver.findElement(By.id("location-input")).sendKeys("Aveiro");
    driver.findElement(By.id("search-button")).click();
    Thread.sleep(1000);
    assertThat(driver.getTitle()).isEqualTo("Air Quality");
    assertThat(driver.findElement(By.cssSelector(".text-center")).getText()).isEqualTo("Air Quality Now");

    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td")).getText()).isEqualTo("Aveiro, PT");
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td")).getText()).isEqualTo("40.640496");
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td")).getText()).isEqualTo("-8.6537841");
  }
}
