package ua.tqs;
// Generated by Selenium IDE
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;


@ExtendWith(SeleniumJupiter.class)
public class BlazeDemoBostonLondonTest {

  @Test
  public void blazeDemoBostonLondon(ChromeDriver driver) {
    driver.get("https://blazedemo.com/");
    driver.manage().window().setSize(new Dimension(1536, 877));
    driver.findElement(By.name("fromPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Boston']")).click();
    }
    driver.findElement(By.name("toPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'London']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Your flight from TLV to SFO has been reserved."));
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText(), is("Airline: United"));
    assertThat(driver.findElement(By.cssSelector("p:nth-child(3)")).getText(), is("Flight Number: UA954"));
    assertThat(driver.findElement(By.cssSelector("p:nth-child(4)")).getText(), is("Price: 400"));
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Tommy Shelby");
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("address")).sendKeys("Peaky Blinder Street");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("Birmingham");
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("zipCode")).click();
    driver.findElement(By.id("zipCode")).sendKeys("1111-999");
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("cardType")).click();
    driver.findElement(By.id("creditCardNumber")).click();
    driver.findElement(By.id("creditCardNumber")).sendKeys("123456789");
    driver.findElement(By.id("nameOnCard")).click();
    driver.findElement(By.id("nameOnCard")).sendKeys("Thomas Shelby");
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Thank you for your purchase today!"));
    assertThat(driver.getTitle(), is("BlazeDemo Confirmation"));
  }
}
