DROP TABLE IF EXISTS dbo.PREFERENCIAS_LITERARIAS;
DROP TABLE IF EXISTS dbo.INTEGRA_COMUNIDADE;
DROP TABLE IF EXISTS dbo.COMUNIDADE;
DROP TABLE IF EXISTS dbo.PERFIL;
DROP TABLE IF EXISTS dbo.FOTOS_DEPOSITO;
DROP TABLE IF EXISTS dbo.FORMULARIO_DEPOSITO;
DROP TABLE IF EXISTS dbo.FORMULARIO_TROCA;
DROP TABLE IF EXISTS dbo.AvaliacaoBookmate;
DROP TABLE IF EXISTS dbo.AvaliacaoEstafeta;
DROP TABLE IF EXISTS dbo.DaGorjeta;
DROP TABLE IF EXISTS dbo.ESTAFETA;
DROP TABLE IF EXISTS dbo.LIVRO;
DROP TABLE IF EXISTS dbo.UTILIZADOR;

CREATE TABLE UTILIZADOR (
	ID INT NOT NULL,
	Fname VARCHAR(30) NOT NULL,
	Lname VARCHAR(30) NOT NULL,
	Username VARCHAR(30) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Birthday DATE NOT NULL,
	GeoLocation VARCHAR(50),
	PRIMARY KEY(ID),
	UNIQUE(ID, Username)
)

CREATE TABLE PREFERENCIAS_LITERARIAS(
	IDuser INT NOT NULL,
	PreferenciaLiteraria VARCHAR(50) NOT NULL,
	PRIMARY KEY(IDuser, PreferenciaLiteraria),
	FOREIGN KEY (IDuser) REFERENCES UTILIZADOR(ID)
	)


CREATE TABLE COMUNIDADE(
	ID	INT NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	GeneroLirico VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE(ID)
)

CREATE TABLE INTEGRA_COMUNIDADE(
	IDuser INT NOT NULL,
	IDcomunidade INT NOT NULL,
	PRIMARY KEY (IDuser, IDcomunidade),
	FOREIGN KEY(IDuser) REFERENCES UTILIZADOR(ID),
	FOREIGN KEY (IDcomunidade) REFERENCES COMUNIDADE(ID)
)

CREATE TABLE PERFIL (
	IDuser INT NOT NULL,
	Endereco VARCHAR(100) NOT NULL,
	Imagem	VARCHAR(100), -- guarda o path da imagem
	Biografia VARCHAR(300),
	PRIMARY KEY(IDuser, Endereco),
	FOREIGN KEY(IDuser) REFERENCES UTILIZADOR(ID)
)

CREATE TABLE LIVRO (
	IDuser INT NOT NULL,
	Codigo INT NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Autor VARCHAR(100) NOT NULL,
	Edicao INT NOT NULL,
	Editora VARCHAR(100) NOT NULL
	PRIMARY KEY(Codigo),
	UNIQUE(Codigo),
	FOREIGN KEY(IDuser) REFERENCES UTILIZADOR(ID)
)

CREATE TABLE FOTOS_DEPOSITO (
	LivroCodigo INT NOT NULL,
	FotoDeposito VARCHAR(100) NOT NULL,
	PRIMARY KEY(FotoDeposito, LivroCodigo),
	FOREIGN KEY(LivroCodigo) REFERENCES LIVRO(Codigo)
)

CREATE TABLE FORMULARIO_DEPOSITO (
	IDuser INT NOT NULL,
	ID INT NOT NULL,
	Data DATE NOT NULL,
	CodigoLivro INT NOT NULL,
	PRIMARY KEY(IDuser, ID),
	FOREIGN KEY(IDuser) REFERENCES UTILIZADOR(ID),
	FOREIGN KEY(CodigoLivro) REFERENCES LIVRO(Codigo)
)

CREATE TABLE ESTAFETA (
	ID INT NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Location VARCHAR(100),
	PRIMARY KEY(ID)
)

CREATE TABLE FORMULARIO_TROCA (
	IDuser1 INT NOT NULL,
	IDuser2 INT NOT NULL,
	ID INT NOT NULL,
	Data DATE NOT NULL,
	DataDeTroca DATE,
	IDestafeta INT,
	CodigoLivro INT,
	PRIMARY KEY(IDuser1, ID),
	FOREIGN KEY (IDuser1) REFERENCES UTILIZADOR(ID),
	FOREIGN KEY (IDuser2) REFERENCES UTILIZADOR(ID)
)

CREATE TABLE AvaliacaoBookMate (
	IDuser1 INT NOT NULL,
	IDuser2 INT,
	ID VARCHAR(10) NOT NULL,
	Conteudo VARCHAR(300),
	Data DATE,
	PRIMARY KEY(IDuser1, ID),
	FOREIGN KEY(IDuser1) REFERENCES UTILIZADOR(ID),
	FOREIGN KEY(IDuser2) REFERENCES UTILIZADOR(ID),
)

CREATE TABLE AvaliacaoEstafeta(
	IDuser INT NOT NULL,
	ID INT NOT NULL,
	Conteudo VARCHAR(300),
	Data DATE,
	IDestafeta INT,
	PRIMARY KEY(IDuser, ID),
	FOREIGN KEY (IDuser) REFERENCES UTILIZADOR(ID),
	FOREIGN KEY (IDestafeta) REFERENCES ESTAFETA(ID),
)

CREATE TABLE DaGorjeta(
	IDuser INT NOT NULL,
	IDestafeta INT NOT NULL,
	Quantia DECIMAL(10,2) NOT NULL,
	Data DATE,
	PRIMARY KEY(IDuser, IDestafeta),
	FOREIGN KEY(IDuser) REFERENCES UTILIZADOR(ID),
	FOREIGN KEY(IDestafeta) REFERENCES ESTAFETA(ID),
)
	