package ua.tqs.hw1.webapp;// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.assertj.core.api.Assertions.assertThat;
@ExtendWith(SeleniumJupiter.class)
public class AirQualityForecastTest {


  @Disabled
  @Test
  public void airQualityForecast(FirefoxDriver driver) throws InterruptedException {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1536, 877));
    driver.findElement(By.linkText("Forecast")).click();
    driver.findElement(By.id("location-input")).click();
    driver.findElement(By.id("location-input")).sendKeys("Aveiro");
    driver.findElement(By.id("search-button")).click();
    Thread.sleep(1000);
    assertThat(driver.getTitle()).isEqualTo("Air Quality - Forecast");
    assertThat(driver.findElement(By.cssSelector(".text-center")).getText()).isEqualTo("Air Quality Forecast");
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(5) > th")).getText()).isEqualTo("Date");
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(9) > th")).getText()).isEqualTo("Date");
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(13) > th")).getText()).isEqualTo("Date");
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(17) > th")).getText()).isEqualTo("Date");
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(21) > th")).getText()).isEqualTo("Date");
  }
}
