# reutilizei a base de dados anteriormente criada nas alíneas, pois não existia conflito de entidades/conceitos
# MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:33060/demo?enabledTLSProtocols=TLSv1.2
spring.datasource.username=demo
spring.datasource.password=secret2
soring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

# Strategy to auto updatethe schemas  (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
